name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: npm install, build
      run: |
        npm install
        CI='' npm run build:staging --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job 
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Copy To Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.REMOTE_SERVER }}
          username: ${{ vars.REMOTE_USER }}
          password: ${{ secrets.USER_PASSWORD }}
          source: "."
          target: /var/www/testniraj.trayistats/test04-03-2024${{ github.run_id }}

      - name: Run Scripts on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.REMOTE_SERVER }}
          username: ${{ vars.REMOTE_USER }}
          password: ${{ secrets.USER_PASSWORD }}
          script: |
            echo ${{ github.run_number }} 
            mkdir -p /var/www/testniraj.trayistats/test04-03-2024${{ github.run_number }}.${{ github.run_attempt }}
            mv -f /var/www/testniraj.trayistats/test04-03-2024/. /var/www/testniraj.trayistats/test04-03-2024${{ github.run_number }}.${{ github.run_attempt }}/
            cp -a /var/www/testniraj.trayistats/test04-03-2024${{ github.run_id }}/. /var/www/testniraj.trayistats/test04-03-2024/
            cp -R /var/www/common/.htaccess /var/www/testniraj.trayistats/test04-03-2024/
            sudo service apache2 restart
            rm -r /var/www/testniraj.trayistats/test04-03-2024${{ github.run_id }}
